# Generated by Django 5.0.6 on 2024-05-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosapp', '0002_userprofile_bio_userprofile_other_data_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='other_data',
        ),
    ]
